[project]
name = "mc-server-backup"
version = "0.1.0"
description = "A python tool to backup Minecraft server folder or any folder"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "watchdog>=6.0.0",
]
